from enum import StrEnum
import uuid
from datetime import datetime, timedelta
from google.cloud import ndb

from . import client


class SocialPlatform(StrEnum):
    REDDIT = "Reddit"
    TWITTER = "Twitter"
    ILLINOIS_APP = "Illinois app"


class SocialPost(ndb.Model):
    title = ndb.StringProperty()
    url = ndb.StringProperty()
    platform = ndb.StringProperty(choices=list(SocialPlatform))
    created_by = ndb.StringProperty()
    created_at = ndb.DateTimeProperty()


def create_post(title, url, platform, created_by):
    with client.context():
        # Story's id is auto generated by using uuid.uuid1() when posting a story
        # created_at will get the current time
        post = SocialPost(
            id=str(uuid.uuid1()),
            title=title,
            url=url,
            platform=platform,
            created_by=created_by,
            created_at=datetime.now(),
        )
        post.put()
    return post.to_dict()


def get_all_posts():
    with client.context():
        posts = [post.to_dict() for post in SocialPost.query().fetch()]
    return posts


def get_recent_posts(count):
    with client.context():
        posts = [
            post.to_dict()
            for post in SocialPost.query()
            .order(-SocialPost.created_at)
            .fetch(limit=count)
        ]
    return posts


def delete_all_posts():
    with client.context():
        posts = SocialPost.query().fetch()
        for post in posts:
            post.key.delete()
    return posts


def get_post(id):
    if id is None:
        return None
    with client.context():
        post = SocialPost.query().filter(SocialPost.id == id).get()
    if post is None:
        return None
    return post


def check_limit(platform, limit, days):
    with client.context():
        current_datetime = datetime.now()
        start_datetime = current_datetime - timedelta(days=days)
        recent_posts = (
            SocialPost.query()
            .filter(
                SocialPost.platform == platform,
                SocialPost.created_at >= start_datetime,
                SocialPost.created_at <= current_datetime,
            )
            .fetch()
        )
    return len(recent_posts) >= limit
