import uuid
import datetime
from google.cloud import ndb

from . import client

class Story(ndb.Model):
    id = ndb.StringProperty()
    title = ndb.StringProperty()
    url = ndb.StringProperty()
    posted_to = ndb.StringProperty()
    posted_at = ndb.DateTimeProperty()


def add_story(title, url, posted_to):
    with client.context():
        # Story's id is auto generated by using uuid.uuid1() when posting a story
        # posted_at will get the current time
        story = Story(id=str(uuid.uuid1()), title=title, url=url, posted_to=posted_to, posted_at=datetime.datetime.now())
        story.put()
    return story


def get_all_stories():
    with client.context():
        stories = [story.to_dict() for story in Story.query().fetch()]
    return stories

def delete_all_stories():
    with client.context():
        stories = Story.query().fetch()
        for story in stories:
            story.key.delete()
    return stories

def get_story(id):
    if id is None:
        return None
    with client.context():
        story = Story.query().filter(Story.id == id).get()
    if story is None:
        return None
    return story